include = ["**/*.toml"]
exclude = ["target/**", "vendor/**", ".git/**"]

[formatting]
align_entries = false
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = false
column_width = 100
compact_inline_tables = false
indent_string = "    "
reorder_keys = false
reorder_arrays = false
allowed_blank_lines = 1
trailing_newline = true
crlf = false
